# Docs on cloudwatch configuration: https://docs.fluentbit.io/manual/pipeline/outputs/cloudwatch
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Configuration
metadata:
  name: logging-config
spec:
  logging:
    outputs:
      - name: stdout
        type: stdout
        parameters:
          format: json_lines
      - name: cloudwatch
        type: cloudwatch_logs
        parameters:
          region: us-east-1
          log_group_name: /mulesoft/flex-dev/
          log_stream_name: flex-gateway-dev.log
          log_format: json
          log_key: message

    runtimeLogs:
      logLevel: info
      outputs:
        - stdout
        - cloudwatch
    accessLogs:
      outputs:
        - stdout
        - cloudwatch
