name: CD
on:
  push:
    branches:
      - main

jobs:
  tfapply:
    strategy:
      matrix:
        TF_DIR:
          [
            ./terraform/env/test,
            ./terraform/env/dev,
            ./terraform/env/prod,
            ./terraform/common,
          ]
    uses: CityOfPhiladelphia/citygeo-shared-workflows/.github/workflows/terraform_apply.yaml@main
    with:
      tf_dir: ${{ matrix.TF_DIR }}
      tf_token_keeper_path: sd33hj2cVYiRB4TEhAG_jg/field/password
      aws_access_key_id_keeper_path: fNW6hNUZMImoX21IaGRcQw/field/login
      aws_secret_access_key_keeper_path: fNW6hNUZMImoX21IaGRcQw/field/password
    secrets: inherit
