name: CD
on: [push, pull_request]

jobs:
  tfplan:
    runs-on: self-hosted
    container: buildpack-deps:bookworm

    strategy:
      matrix:
        TF_DIR: [./terraform/env/test, ./terraform/env/dev]

    steps:
      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            sd33hj2cVYiRB4TEhAG_jg/field/password > env:TF_TOKEN
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ env.TF_TOKEN }}
      - name: Terraform Init
        run: |
          cd ${{ matrix.TF_DIR }}
          terraform init
      - name: Terraform Plan
        run: |
          cd ${{ matrix.TF_DIR }}
          terraform plan
        env:
          KEEPER_CREDENTIAL: ${{ secrets.KSM_CONFIG }}
