name: CI
on: [push, pull_request]

env:
  TF_DIR: "./terraform"

jobs:
  truflehog:
    runs-on: self-hosted
    container: buildpack-deps:bookworm
    steps:
      - name: Install requirements
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y jq
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Trufflehog OSS
        uses: trufflesecurity/trufflehog@add-actions-cli-switch
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --debug --only-verified
      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
  tflint:
    runs-on: self-hosted
    container: buildpack-deps:bookworm

    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - name: Calculate tflint config hash
        id: hash
        run: |
          echo "hash=$(sha256sum $TF_DIR/.tflint.hcl | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ steps.hash.outputs.hash }}

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: latest

      - name: Show version
        run: |
          cd $TF_DIR
          tflint --version

      - name: Init TFLint
        run: |
          cd $TF_DIR
          tflint --init

      - name: Run TFLint
        run: |
          cd $TF_DIR
          tflint -f compact
