name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  TF_DIR: "./terraform"

jobs:
  shellcheck:
    uses: CityOfPhiladelphia/citygeo-shared-workflows/.github/workflows/shellcheck.yaml@main
    with:
      files: "server/build.sh"
      cli_opts: "-e SC2155"
  terraform_fmt:
    uses: CityOfPhiladelphia/citygeo-shared-workflows/.github/workflows/terraform_fmt.yaml@main
    with:
      parent_tf_dir: "./terraform"

  tflint:
    uses: CityOfPhiladelphia/citygeo-shared-workflows/.github/workflows/tflint.yaml@main
    with:
      parent_tf_dir: "./terraform"
      github_token: ${{ github.token }}

  tfplan:
    runs-on: self-hosted
    container: buildpack-deps:bookworm

    strategy:
      matrix:
        TF_DIR:
          [./terraform/env/test, ./terraform/env/dev, ./terraform/env/prod]

    steps:
      - uses: actions/checkout@v4
        name: Checkout source code
      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            sd33hj2cVYiRB4TEhAG_jg/field/password > env:TF_TOKEN
            fNW6hNUZMImoX21IaGRcQw/field/login > env:AWS_ACCESS_KEY_ID
            fNW6hNUZMImoX21IaGRcQw/field/password > env:AWS_SECRET_ACCESS_KEY
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ env.TF_TOKEN }}
      - name: Terraform Init
        run: |
          cd ${{ matrix.TF_DIR }}
          terraform init
      - name: Terraform Plan
        run: |
          cd ${{ matrix.TF_DIR }}
          terraform plan -lock-timeout=30s
        env:
          KEEPER_CREDENTIAL: ${{ secrets.KSM_CONFIG }}
