name: Lint
on: [push, pull_request]

env:
  TERRAFORM_FOLDER: "./terraform"

jobs:
  tflint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('$TERRAFORM_FOLDER/.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: latest

      - name: Show version
        run: tflint --version
        working-directory: $TERRAFORM_FOLDER

      - name: Init TFLint
        run: tflint --init
        working-directory: $TERRAFORM_FOLDER

      - name: Run TFLint
        run: tflint -f compact
        working-directory: $TERRAFORM_FOLDER
