name: Refresh Flex Gateway Cert
on:
  push:

jobs:
  get_cert:
    runs-on: self-hosted

    steps:
      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            ahJIwNclElg70ifRs7T1qw/field/password > env:PASSWORD
      - name: List home dir
        run: |
          echo $PASSWORD
