name: Refresh Flex Gateway Cert
on:
  push:

jobs:
  refresh:
    runs-on: self-hosted
    container: buildpack-deps:bookworm

    steps:
      - name: Create registration directory
        run: |
          mkdir /tmp/fg_cfg
      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            lv4qSA1x9r_hBnPhx-HX_A/file/mulesoft_test_reg.yml > file:/tmp/fg_cfg/registration.yaml
            LXdIN2HmAPOOPec9x79Iew/field/login > env:FLEXCTL_LOGIN
            LXdIN2HmAPOOPec9x79Iew/field/password > env:FLEXCTL_PASSWORD
      - name: Docker pull flex-Gateway
        run: |
          docker pull mulesoft/flex-gateway:latest
      - name: Check registration
        run: |
          docker run --entrypoint flexctl \
          -v "/tmp/fg_cfg":/registration mulesoft/flex-gateway \
          registration inspect
