name: Refresh Flex Gateway Cert
on:
  push:

jobs:
  get_cert:
    runs-on: self-hosted
    container: buildpack-deps:bookworm

    steps:
      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            lv4qSA1x9r_hBnPhx-HX_A/file/mulesoft_test_reg.yml > file:mulesoft_test_reg.yml
            LXdIN2HmAPOOPec9x79Iew/field/login > env:FLEXCTL_LOGIN
            LXdIN2HmAPOOPec9x79Iew/field/password > env:FLEXCTL_PASSWORD
      - name: List home dir
        run: |
          ls
          pwd
          echo $FLEXCTL_PASSWORD
          echo $FLEXCTL_LOGIN
